using OrderCloud.SDK;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace OrderCloud.Catalyst
{
	/// <summary>
	/// An interface to define the behavior of a credit card processor. Full CC details are never passed to it, as that would put it in PCI compliance scope. Instead, it accepts iframe generated tokens or saved card IDs.
	/// </summary>
	public interface ICreditCardProcessor
	{
		/// <summary>
		/// Attempt to verify the user can pay by placing a hold on a credit card. Funds will be captured later. Typically used as a verification step directly before order submit.
		/// </summary>
		Task<CCTransactionResult> AuthorizeOnlyAsync(AuthorizeCCTransaction transaction, OCIntegrationConfig overrideConfig = null);
		/// <summary>
		/// Attempt to capture funds from a credit card. A prior authorization is required. Typically used when a shipment is created, at the end of the day, or a defined time period after submit.
		/// </summary>
		Task<CCTransactionResult> CapturePriorAuthorizationAsync(FollowUpCCTransaction transaction, OCIntegrationConfig overrideConfig = null);
		/// <summary>
		/// Remove an authorization hold previously placed on a credit card. Use if order submit fails, or if order is canceled/returned before capture. 
		/// </summary>
		Task<CCTransactionResult> VoidAuthorizationAsync(FollowUpCCTransaction transaction, OCIntegrationConfig overrideConfig = null);
		/// <summary>
		/// Refund previously a captured amount. Used if an order is canceled/returned after capture. Refunding generally incures extra processing fees, whereas voiding does not.
		/// </summary>
		Task<CCTransactionResult> RefundCaptureAsync(FollowUpCCTransaction transaction, OCIntegrationConfig overrideConfig = null);
	}

	public class AuthorizeCCTransaction
	{
		/// <summary>
		/// The OrderCloud Order ID that this card transaction applies to.
		/// </summary>
		public string OrderID { get; set; }
		/// <summary>
		/// The ammount that will be authorized on the credit card.
		/// </summary>
		public decimal Amount { get; set; }
		/// <summary>
		/// The currency to authorize in - three letter ISO format. 
		/// </summary>
		public string Currency { get; set; }
		/// <summary>
		/// A secure, tokenized representation of a one-time use credit card. Generated by a specific processor system. 
		/// </summary>
		public string CardToken { get; set; }
		/// <summary>
		/// If true, will attempt payment with SavedCardID. If false, will attempt payment with CardToken.
		/// </summary>
		public bool PayWithSavedCard { get; set; } = false;
		/// <summary>
		/// The ID of a multi-use credit card saved in the processor system.
		/// </summary>
		public string SavedCardID { get; set; }
		/// <summary>
		/// The ID of a customer record in the processor system. Needed if paying with a saved credit card.
		/// </summary>
		public string ProcessorCustomerID { get; set; }
		/// <summary>
		/// Address verification (AVS) is an optional layer of security for payments. It checks a customer-provided street and zip code against the records on file with the card issuer. 
		/// </summary>
		public Address AddressVerification { get; set; }
		/// <summary>
		/// The customer's IP address is typically not required by processors, but it provides a layer of insurance on disputed or fraudulent payments. 
		/// </summary>
		public string CustomerIPAddress { get; set; }
	}

	public class CCTransactionResult
	{
		/// <summary>
		/// Did the transaction succeed?
		/// </summary>
		public bool Succeeded { get; set; }
		/// <summary>
		/// The processor-generated ID for this action. Null if a create attempt failed. 
		/// </summary>
		public string TransactionID { get; set; }
		/// <summary>
		/// The raw processor-specific response code. Depending on the processor, typical meaninings include Approved, Declined, Held For Review, Retry, Error.
		/// </summary>
		public string ResponseCode { get; set; }
		/// <summary>
		/// The authorization code granted by the card issuing bank for this transaction. Should be 6 characters, e.g. "HH5414".
		/// </summary>
		public string AuthorizationCode { get; set; }
		/// <summary>
		/// A code explaining the result of address verification (AVS). Whether to perform AVS is typically configured at the processor level. Standard 1 character result codes, see https://www.merchantmaverick.com/what-is-avs-for-credit-card-processing/.  
		/// </summary>
		public string AVSResponseCode { get; set; }
		/// <summary>
		/// User readable text explaining the result.
		/// </summary>
		public string Message { get; set; }
	}

	/// <summary>
	/// A credit card transaction that follows after a successfull authorization such as capture, void, or refund.
	/// </summary>
	public class FollowUpCCTransaction
	{
		/// <summary>
		/// The processor-generated ID of the original authorize transaction.
		/// </summary>
		public string TransactionID { get; set; }
		/// <summary>
		/// The amount to capture, void, or refund. If null, will default to the full amount of the existing transaction.
		/// </summary>
		public decimal Amount { get; set; }
	}
}
